name: hpc-core CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      # Tests: wir nutzen den Dev-Stub (kein echtes OpenCL nötig)
      - name: Test (trybuild + unit tests)
        run: cargo test -p hpc-core --tests -- --nocapture
        env:
          RUSTFLAGS: "--cfg hpc_core_dev"

      # Lints: nur lib + tests streng (Examples/Benches bleiben außen vor)
      - name: Clippy (lib + tests, deny warnings)
        run: cargo clippy -p hpc-core --lib --tests -- -D warnings
        env:
          RUSTFLAGS: "--cfg hpc_core_dev"


      # optional: Doku baut
      - name: Cargo doc (sanity)
        run: cargo doc -p hpc-core
        env:
          RUSTFLAGS: "--cfg hpc_core_dev"